/// PackageController
/// 商品/套餐数据管理

import 'package:get/get.dart';
import '../models/package_item.dart';

class PackageController extends GetxController {
  final allPackages = <PackageItem>[
    // 游戏币套餐
    PackageItem(
      id: '1',
      name: '游戏币套餐A',
      description: '充值100迪拉姆 + 20超级币 + 12寸毛绒玩具',
      price: 100.00,
      category: 'game_coin_package',
    ),
    PackageItem(
      id: '2',
      name: '游戏币套餐B',
      description: '充值200迪拉姆 + 50超级币 + 限量手办',
      price: 200.00,
      category: 'game_coin_package',
    ),
    PackageItem(
      id: '3',
      name: '游戏币套餐C',
      description: '充值50迪拉姆 + 10超级币',
      price: 50.00,
      category: 'game_coin_package',
      stock: 0,
    ),
    PackageItem(
      id: '18',
      name: '游戏币套餐D',
      description: '充值500迪拉姆 + 150超级币 + 限量周边礼盒',
      price: 500.00,
      category: 'game_coin_package',
    ),
    PackageItem(
      id: '19',
      name: '游戏币套餐E',
      description: '充值300迪拉姆 + 80超级币 + 精美文具套装',
      price: 300.00,
      category: 'game_coin_package',
    ),
    PackageItem(
      id: '20',
      name: '游戏币套餐F',
      description: '充值150迪拉姆 + 35超级币 + 小型玩偶',
      price: 150.00,
      category: 'game_coin_package',
    ),
    PackageItem(
      id: '21',
      name: '游戏币套餐G',
      description: '充值80迪拉姆 + 15超级币',
      price: 80.00,
      category: 'game_coin_package',
      stock: 0,
    ),
    PackageItem(
      id: '22',
      name: '游戏币套餐H',
      description: '充值1000迪拉姆 + 300超级币 + VIP专属礼包',
      price: 1000.00,
      category: 'game_coin_package',
    ),
    PackageItem(
      id: '23',
      name: '游戏币套餐I',
      description: '充值600迪拉姆 + 180超级币 + 定制抱枕',
      price: 600.00,
      category: 'game_coin_package',
      stock: 0,
    ),
    PackageItem(
      id: '24',
      name: '游戏币套餐J',
      description: '充值250迪拉姆 + 60超级币 + 徽章套装',
      price: 250.00,
      category: 'game_coin_package',
    ),

    // 超级币套餐
    PackageItem(
      id: '4',
      name: '超级币套餐A',
      description: '100超级币',
      price: 150.00,
      category: 'super_coin_package',
    ),
    PackageItem(
      id: '5',
      name: '超级币套餐B',
      description: '200超级币 + 精美礼盒',
      price: 280.00,
      category: 'super_coin_package',
    ),

    // 引流
    PackageItem(
      id: '6',
      name: '引流兑换券A',
      description: '新人引流专用券',
      price: 30.00,
      category: 'promotion',
      validFrom: DateTime(2025, 1, 1),
      validTo: DateTime(2025, 12, 31),
    ),
    PackageItem(
      id: '14',
      name: '引流兑换券B',
      description: '节假日引流专用券',
      price: 50.00,
      category: 'promotion',
      validFrom: DateTime(2025, 6, 1),
      validTo: DateTime(2025, 6, 30),
    ),
    PackageItem(
      id: '25',
      name: '引流兑换券C',
      description: '周末引流专用券',
      price: 40.00,
      category: 'promotion',
      validFrom: DateTime(2025, 3, 1),
      validTo: DateTime(2025, 3, 31),
    ),
    PackageItem(
      id: '26',
      name: '引流兑换券D',
      description: '学生专属引流券',
      price: 25.00,
      category: 'promotion',
      validFrom: DateTime(2025, 1, 1),
      validTo: DateTime(2025, 8, 31),
      stock: 0,
    ),
    PackageItem(
      id: '27',
      name: '引流兑换券E',
      description: '家庭套餐引流券',
      price: 80.00,
      category: 'promotion',
      validFrom: DateTime(2025, 1, 1),
      validTo: DateTime(2025, 12, 31),
    ),
    PackageItem(
      id: '28',
      name: '引流兑换券F',
      description: '生日专属引流券',
      price: 60.00,
      category: 'promotion',
      validFrom: DateTime(2025, 1, 1),
      validTo: DateTime(2025, 12, 31),
      stock: 0,
    ),

    // 机台兑币
    PackageItem(
      id: '7',
      name: '机台兑币券A',
      description: '指定机台兑换券',
      price: 50.00,
      category: 'machine_exchange',
      validFrom: DateTime(2025, 1, 1),
      validTo: DateTime(2025, 12, 31),
    ),
    PackageItem(
      id: '15',
      name: '机台兑币券B',
      description: '全场机台通用券',
      price: 80.00,
      category: 'machine_exchange',
      validFrom: DateTime(2025, 1, 1),
      validTo: DateTime(2025, 12, 31),
      stock: 0,
    ),
    PackageItem(
      id: '29',
      name: '机台兑币券C',
      description: '娃娃机专用券',
      price: 40.00,
      category: 'machine_exchange',
      validFrom: DateTime(2025, 1, 1),
      validTo: DateTime(2025, 6, 30),
    ),
    PackageItem(
      id: '30',
      name: '机台兑币券D',
      description: '赛车游戏专用券',
      price: 60.00,
      category: 'machine_exchange',
      validFrom: DateTime(2025, 1, 1),
      validTo: DateTime(2025, 12, 31),
      stock: 0,
    ),
    PackageItem(
      id: '31',
      name: '机台兑币券E',
      description: '射击游戏专用券',
      price: 55.00,
      category: 'machine_exchange',
      validFrom: DateTime(2025, 2, 1),
      validTo: DateTime(2025, 12, 31),
    ),
    PackageItem(
      id: '32',
      name: '机台兑币券F',
      description: '音乐游戏专用券',
      price: 45.00,
      category: 'machine_exchange',
      validFrom: DateTime(2025, 1, 1),
      validTo: DateTime(2025, 9, 30),
    ),
    PackageItem(
      id: '33',
      name: '机台兑币券G',
      description: 'VR体验专用券',
      price: 100.00,
      category: 'machine_exchange',
      validFrom: DateTime(2025, 1, 1),
      validTo: DateTime(2025, 12, 31),
    ),

    // 刮刮卡
    PackageItem(
      id: '8',
      name: '幸运刮刮卡',
      description: '刮刮卡 x10张',
      price: 80.00,
      category: 'scratch_card',
      validFrom: DateTime(2025, 1, 1),
      validTo: DateTime(2025, 3, 31),
    ),
    PackageItem(
      id: '16',
      name: '超级刮刮卡',
      description: '刮刮卡 x20张',
      price: 150.00,
      category: 'scratch_card',
      validFrom: DateTime(2025, 1, 1),
      validTo: DateTime(2025, 6, 30),
    ),
    PackageItem(
      id: '34',
      name: '入门刮刮卡',
      description: '刮刮卡 x5张',
      price: 40.00,
      category: 'scratch_card',
      validFrom: DateTime(2025, 1, 1),
      validTo: DateTime(2025, 12, 31),
      stock: 0,
    ),
    PackageItem(
      id: '35',
      name: '黄金刮刮卡',
      description: '刮刮卡 x30张',
      price: 220.00,
      category: 'scratch_card',
      validFrom: DateTime(2025, 1, 1),
      validTo: DateTime(2025, 12, 31),
    ),
    PackageItem(
      id: '36',
      name: '钻石刮刮卡',
      description: '刮刮卡 x50张',
      price: 350.00,
      category: 'scratch_card',
      validFrom: DateTime(2025, 1, 1),
      validTo: DateTime(2025, 12, 31),
      stock: 0,
    ),
    PackageItem(
      id: '37',
      name: '周末刮刮卡',
      description: '刮刮卡 x15张',
      price: 100.00,
      category: 'scratch_card',
      validFrom: DateTime(2025, 4, 1),
      validTo: DateTime(2025, 4, 30),
      stock: 0,
    ),

    // 市场活动
    PackageItem(
      id: '9',
      name: '市场活动券',
      description: '限时活动专用券',
      price: 60.00,
      category: 'marketing_activity',
      validFrom: DateTime(2025, 2, 1),
      validTo: DateTime(2025, 2, 28),
    ),
    PackageItem(
      id: '17',
      name: '周年庆活动券',
      description: '周年庆专属优惠券',
      price: 100.00,
      category: 'marketing_activity',
      validFrom: DateTime(2025, 11, 1),
      validTo: DateTime(2025, 11, 30),
    ),
    PackageItem(
      id: '38',
      name: '春节特惠券',
      description: '春节专属优惠券',
      price: 88.00,
      category: 'marketing_activity',
      validFrom: DateTime(2025, 1, 20),
      validTo: DateTime(2025, 2, 10),
    ),
    PackageItem(
      id: '39',
      name: '暑期狂欢券',
      description: '暑期活动专用券',
      price: 120.00,
      category: 'marketing_activity',
      validFrom: DateTime(2025, 7, 1),
      validTo: DateTime(2025, 8, 31),
    ),
    PackageItem(
      id: '40',
      name: '双11特惠券',
      description: '双11限定优惠券',
      price: 150.00,
      category: 'marketing_activity',
      validFrom: DateTime(2025, 11, 1),
      validTo: DateTime(2025, 11, 11),
      stock: 0,
    ),
    PackageItem(
      id: '41',
      name: '圣诞狂欢券',
      description: '圣诞节专属券',
      price: 130.00,
      category: 'marketing_activity',
      validFrom: DateTime(2025, 12, 20),
      validTo: DateTime(2025, 12, 31),
    ),
    PackageItem(
      id: '42',
      name: '会员专享券',
      description: '会员等级升级专用',
      price: 200.00,
      category: 'marketing_activity',
      validFrom: DateTime(2025, 1, 1),
      validTo: DateTime(2025, 12, 31),
      stock: 0,
    ),

    // 小食品
    PackageItem(
      id: '10',
      name: '薯片套装',
      description: '多种口味薯片组合',
      price: 25.00,
      category: 'snacks',
      specification: '5包装/袋',
      stock: 50,
    ),
    PackageItem(
      id: '11',
      name: '巧克力礼盒',
      description: '进口巧克力礼盒装',
      price: 45.00,
      category: 'snacks',
      specification: '500g/盒',
      stock: 30,
    ),
    PackageItem(
      id: '43',
      name: '曲奇饼干',
      description: '丹麦黄油曲奇',
      price: 35.00,
      category: 'snacks',
      specification: '454g/盒',
      stock: 25,
    ),
    PackageItem(
      id: '44',
      name: '坚果礼包',
      description: '混合坚果大礼包',
      price: 68.00,
      category: 'snacks',
      specification: '750g/盒',
      stock: 15,
    ),
    PackageItem(
      id: '45',
      name: '糖果罐',
      description: '水果软糖组合装',
      price: 28.00,
      category: 'snacks',
      specification: '400g/罐',
      stock: 8,
    ),
    PackageItem(
      id: '46',
      name: '爆米花',
      description: '焦糖味爆米花',
      price: 18.00,
      category: 'snacks',
      specification: '200g/袋',
      stock: 0,
    ),
    PackageItem(
      id: '47',
      name: '果冻布丁',
      description: '椰果果冻组合',
      price: 22.00,
      category: 'snacks',
      specification: '12杯/盒',
      stock: 40,
    ),
    PackageItem(
      id: '48',
      name: '威化饼干',
      description: '榛子巧克力威化',
      price: 32.00,
      category: 'snacks',
      specification: '300g/盒',
      stock: 35,
    ),
    PackageItem(
      id: '55',
      name: '进口牛肉干',
      description: '澳洲原味牛肉干',
      price: 58.00,
      category: 'snacks',
      specification: '250g/袋',
      stock: 0,
    ),

    // 饮料
    PackageItem(
      id: '12',
      name: '可乐',
      description: '罐装可乐',
      price: 8.00,
      category: 'beverages',
      specification: '330ml/罐',
      stock: 100,
    ),
    PackageItem(
      id: '13',
      name: '矿泉水',
      description: '瓶装矿泉水',
      price: 5.00,
      category: 'beverages',
      specification: '500ml/瓶',
      stock: 150,
    ),
    PackageItem(
      id: '49',
      name: '橙汁',
      description: '鲜榨橙汁',
      price: 12.00,
      category: 'beverages',
      specification: '350ml/瓶',
      stock: 60,
    ),
    PackageItem(
      id: '50',
      name: '雪碧',
      description: '柠檬味汽水',
      price: 8.00,
      category: 'beverages',
      specification: '330ml/罐',
      stock: 80,
    ),
    PackageItem(
      id: '51',
      name: '冰红茶',
      description: '柠檬红茶饮料',
      price: 10.00,
      category: 'beverages',
      specification: '500ml/瓶',
      stock: 70,
    ),
    PackageItem(
      id: '52',
      name: '椰汁',
      description: '椰树牌椰子汁',
      price: 15.00,
      category: 'beverages',
      specification: '1L/瓶',
      stock: 5,
    ),
    PackageItem(
      id: '53',
      name: '咖啡',
      description: '即饮拿铁咖啡',
      price: 18.00,
      category: 'beverages',
      specification: '270ml/瓶',
      stock: 45,
    ),
    PackageItem(
      id: '54',
      name: '运动饮料',
      description: '蓝莓味功能饮料',
      price: 14.00,
      category: 'beverages',
      specification: '600ml/瓶',
      stock: 55,
    ),
    PackageItem(
      id: '56',
      name: '果汁茶',
      description: '蜜桃乌龙茶',
      price: 16.00,
      category: 'beverages',
      specification: '500ml/瓶',
      stock: 0,
    ),
  ];

  List<PackageItem> getPackagesByCategory(String category) {
    return allPackages.where((pkg) => pkg.category == category).toList();
  }
}
